# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pb.relay_node_pb2 as relay__node__pb2


class RelayNodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.processAi = channel.unary_unary(
                '/relay_node.RelayNode/processAi',
                request_serializer=relay__node__pb2.FromRelayNodeRequest.SerializeToString,
                response_deserializer=relay__node__pb2.FromRelayNodeResponse.FromString,
                )
        self.processGameState = channel.unary_unary(
                '/relay_node.RelayNode/processGameState',
                request_serializer=relay__node__pb2.GameStateRequest.SerializeToString,
                response_deserializer=relay__node__pb2.GameStateResponse.FromString,
                )


class RelayNodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def processAi(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def processGameState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RelayNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'processAi': grpc.unary_unary_rpc_method_handler(
                    servicer.processAi,
                    request_deserializer=relay__node__pb2.FromRelayNodeRequest.FromString,
                    response_serializer=relay__node__pb2.FromRelayNodeResponse.SerializeToString,
            ),
            'processGameState': grpc.unary_unary_rpc_method_handler(
                    servicer.processGameState,
                    request_deserializer=relay__node__pb2.GameStateRequest.FromString,
                    response_serializer=relay__node__pb2.GameStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'relay_node.RelayNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RelayNode(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def processAi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/relay_node.RelayNode/processAi',
            relay__node__pb2.FromRelayNodeRequest.SerializeToString,
            relay__node__pb2.FromRelayNodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def processGameState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/relay_node.RelayNode/processGameState',
            relay__node__pb2.GameStateRequest.SerializeToString,
            relay__node__pb2.GameStateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
